[build]
  command = "npm run build"
  publish = "out"

[[plugins]]
  package = "@netlify/plugin-nextjs"
[[plugins]]
  package = "netlify-plugin-cache-nextjs"

[context.production.environment]
NODE_OPTIONS = "--max_old_space_size=16000"
NEXT_SERVERLESS = "true"
NODE_ENV = "production"